### ISSUE TITLE
Hello, I would like to ask you about the RGRG paper, can I add your WeChat！Thank you！

### ISSUE THREAD

**Issue by Cckyrie** [Liqq1/awesome-medical-vision-and-language-pretraining#1]

**Comment by Liqq1** [comment]
hey, you can send your WeChat ID to my email [qingqiuli0811@gmail.com](mailto:qingqiuli0811@gmail.com)

**Comment by Cckyrie** [comment]
@Liqq1 Thank you!I have already sent my WeChat ID to your Google email.
